export function createBaseState() {
    return {
        data: [],
        originalData: [],
        dataById: new Map(),
        originalDataById: new Map(),
        modifiedCount: 0,
        sortColumn: null,
        sortDirection: 'asc',
        selectedIds: new Set(),
        lastToggled: null,
        editGeneration: 0,
        _activeCellEdit: null,
        currentFilter: '',
        visibleIds: [],
        undoStack: [],
        changeLog: [],
        exportReviewCandidates: new Map(),
        settingsStorageKey: 'tidyscore-settings',
        settings: null,
        _notificationQueue: [],
        _notificationActive: false,
        scanResults: null,
        sourceFileName: 'forscore-library.csv',
        recoveryEnabled: false,
        recoveryPreferenceKey: 'tidyscore-recovery-enabled',
        savedSession: null,
        savedSessionInvalid: false,
        managerTab: 'genres',
        managerData: [],
        managerSelectedValues: new Set(),
        managerFilterText: '',
        _fileReadGeneration: 0,
        _activeFileReader: null
    };
}
