export const baseState = {
    data: [],
    originalData: [],
    dataById: new Map(),
    modifiedCount: 0,
    sortColumn: null,
    sortDirection: 'asc',
    selectedIds: new Set(),
    lastToggled: null,
    editGeneration: 0,
    currentFilter: '',
    visibleIds: [],
    undoStack: [],
    changeLog: [],
    settingsStorageKey: 'tidyscore-settings',
    settings: null,
    _notificationQueue: [],
    _notificationActive: false,
    scanResults: null,
    sourceFileName: 'forscore-library.csv',
    recoveryEnabled: false,
    recoveryPreferenceKey: 'tidyscore-recovery-enabled',
    savedSession: null,
};
